In [1]:
data = [4,63,6,2,5]
data

[4, 63, 6, 2, 5]

In [2]:
type(data)

list

In [4]:
import numpy

In [5]:
data_np = numpy.array(data)

In [6]:
data_np

array([ 4, 63,  6,  2,  5])

In [7]:
import numpy as np
data_np = np.array(data)

In [8]:
type(data_np)

numpy.ndarray

In [9]:
data_np.ndim

1

In [10]:
data_np.shape

(5,)

In [11]:
new_data = np.array([4,5,7,34,2,54])

In [12]:
new_data

array([ 4,  5,  7, 34,  2, 54])

In [16]:
data_2d = np.array([
    [4,6,7,9,2],
    [4,6,7,9]
])

In [17]:
data_2d.shape

(2,)

In [23]:
data = [i for i in range(30)]

In [31]:
data_np = np.arange(50)

In [34]:
data_np.reshape(10,6)

ValueError: cannot reshape array of size 50 into shape (10,6)

In [35]:
data = np.arange(50)

In [36]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
data[5]

5

In [38]:
data[5:30]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
data[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
data = np.arange(60)

In [41]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
data = data.reshape(4, 3, 5)

In [44]:
data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [45]:
data[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
data.shape

(4, 3, 5)

In [47]:
data[3]

array([[45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [54]:
data[0,1,0:4]

array([5, 6, 7, 8])

In [64]:
data = data.reshape(5, 2, 2, 3)

In [66]:
data

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]]]])

In [69]:
data[0,1,1,:]

array([ 9, 10, 11])

In [71]:
data[..., 0]

array([[[ 0,  3],
        [ 6,  9]],

       [[12, 15],
        [18, 21]],

       [[24, 27],
        [30, 33]],

       [[36, 39],
        [42, 45]],

       [[48, 51],
        [54, 57]]])

In [73]:
data.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [74]:
data = data.reshape(12, 5)

In [75]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [76]:
data.transpose()

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])